# Copyright 2025 NXP
#
# SPDX-License-Identifier: BSD-3-Clause
set(ARMGCC_COMPILER_MINIMUM_VERSION 13.2.1 PARENT_SCOPE)
set(MDK_COMPILER_MINIMUM_VERSION 6.22 PARENT_SCOPE)
set(IAR_COMPILER_MINIMUM_VERSION 9.60.3 PARENT_SCOPE)
set(XCC_COMPILER_MINIMUM_VERSION 10.0.1 PARENT_SCOPE)
set(XTENSA_COMPILER_MINIMUM_VERSION 10.0.1 PARENT_SCOPE)
set(CODEWARRIOR_COMPILER_MINIMUM_VERSION 8.3.1 PARENT_SCOPE)
set(RISCVLLVM_COMPILER_MINIMUM_VERSION 19.1.7 PARENT_SCOPE)
set(CMAKE_MINIMUM_VERSION 3.30.0 PARENT_SCOPE)
set(NINJA_MINIMUM_VERSION 1.12.0 PARENT_SCOPE)
set(PYTHON_MINIMUM_VERSION 3.8 PARENT_SCOPE)
set(RUBY_MINIMUM_VERSION 3.1.2 PARENT_SCOPE)