# Copyright 2024, 2025 NXP
#
# SPDX-License-Identifier: BSD-3-Clause
require 'logger'
require 'json'
require 'pathname'
require 'fileutils'
require 'deep_merge'
require_relative '../utils/utils'
require_relative '../utils/sdk_utils'
class NinjaParser
  include SDKGenerator::SDKUtils
  REPO_ROOT_PATH = File.expand_path(File.join(File.dirname(__FILE__), '../../..'))
  NO_GUI_TEMPLATE_TOOLCHAIN = %w[armgcc xcc xclang riscvllvm]
  CUSTOM_COMMAND_IGNORE_LIST = %w[pristine menuconfig guiconfig hardenconfig guiproject
    standalone_project manifest flash debug debugserver attach usage ram_report rom_report
    footprint]
  # Tool-level config settings where the yml (IDE.yml) definition wins over
  # the CMake-parsed one (i.e., do NOT concatenate the two arrays). Add any
  # future setting that should follow the same rule here.
  YML_OVERRIDE_TOOL_CONFIG_SETTINGS = %w[lib-search-path]

  def initialize(ninja, name, toolchain, config, outdir, logger)
    @logger = Logger.new(STDOUT)
    @ninja = ninja
    @name = name
    @toolchain = toolchain
    @config = config
    @outdir = outdir
    @logger = logger
    @data = prepare_data(name, toolchain, config, outdir)
    # files recorded but not exist, used to check whether it is generated by build command
    @non_existent_files = []
  end

  def process
    read_ninja
    parse_cc_flags
    parse_cx_flags
    parse_as_flags
    parse_ld_flags
    parse_source
    parse_header
    parse_exclude_files
    parse_libraries
    parse_as_include_path
    parse_cc_include_path
    parse_cx_include_path
    parse_prebuild
    parse_postbuild
    parse_precompile
    parse_cmake_custom_command
    parse_custom_target_dependencies
    parse_example_readme
    merge_ide_data
    set_project_language
    remove_unsupported_config
    {"set.board.#{ENV['board']}" => @data}
  end

  def prepare_data(name, toolchain, config, outdir)
    data = {
      @name => {
        'section-type' => ENV['project_type']  == 'LIBRARY' ? 'library' : 'application',
        'required' => true,
        'belong_to' => "set.board.#{ENV['board']}",
        'contents' => {
          'configuration' => {
            'tools'=> {
              toolchain => {
                'config' => {
                  config => {
                    'identity' => config,
                    'target' => config,
                    'cc-define' => {},
                    'cx-define' => {},
                    'as-define' => {},
                    'as-flags' => [],
                    'cc-flags' => [],
                    'cx-flags' => [],
                    'ld-flags' => [],
                    'cp-define' => {},
                  }
                }
              }
            }
          },
          'document' => {
            'name' => @name,
            'platform_devices_soc_name' => ENV['device'],
            'board' => ENV['board'],
            'core' => ENV['core'],
            'core_id' => ENV['core_id'],
            'fpu' => ENV['fpu'],
            'dsp' => ENV['dsp'],
            'trustzone' => ENV['trustzone'],
            'toolchains' => [toolchain],
            'compilers' => [get_compiler(toolchain)]
          },
          # Use build dir as gui porject root dir to short output path, because IDE such as mdk/iar may report too deep path error
          # it can also simply toolchain setting
          'project-root-path' => ".",
          'modules' => {
            'demo' => {
              'required' => true,
              'cc-include' => [],
              'as-include' => [],
              'cx-include' => [],
              'files' => [],
            }
          }
        },
        'dependency' => [],
        'project_tags' => name,
        'depended_set' => []
      }
    }
    if ENV['IDE_TEMPLATE'] == 'undefined'
      raise "ERROR: IDE template is not defined, please add it by mcux_set_ide_template function"
    end
    data
  end

  def get_project_root_path
    root_folder = File.dirname(File.expand_path(File.join(__FILE__, "../../.."))).split(File::SEPARATOR).last
    path_parts = ENV['APPLICATION_SOURCE_DIR'].split(File::SEPARATOR)
    index = path_parts.rindex(root_folder)
    result = if index
      File.join(path_parts[index + 1..-1])
    else
      @name
    end
    if ENV['is_multicore_device'] == 'y'
      File.join(result, ENV['core_id'])
    else
      result
    end
  end

  def read_ninja
    @content = []
    begin
      file = File.open(@ninja, 'rb')
      @content = file.readlines
      file.close
    rescue StandardError => e
      @logger.error("read file error #{@ninja}: #{e.message} ")
    end
  end

  def get_compiler(toolchain)
    type_map = {
      'iar' => 'iar',
      'mdk' => 'arm',
      'armgcc' => 'gcc',
      'mcux' => 'gcc',
      'armds' => 'arm',
      'codewarrior' => 'mwcc56800e',
      'xtensa' => 'xcc',
      'riscvllvm' => 'riscvllvm'
    }
    type_map[toolchain]
  end

  def get_pattern(type)
    type_map = {
        'cc' => /^build\sCMakeFiles\S+\.o(bj)?:\sC_COMPILER/,
        'cx' => /^build\sCMakeFiles\S+\.o(bj)?:\sCXX_COMPILER/,
        'as' => /^build\sCMakeFiles\S+\.o(bj)?:\sASM_COMPILER/
    }
    type_map[type]
  end
  def parse_cc_flags
    parse_flags(get_pattern('cc'), 'cc')
  end
  def parse_cx_flags
    parse_flags(get_pattern('cx'), 'cx')
  end
  def parse_as_flags
    parse_flags(get_pattern('as'), 'as')
  end

  def parse_cc_include_path
    parse_include_path(get_pattern('cc'), 'cc')
  end

  def parse_cx_include_path
    parse_include_path(get_pattern('cx'), 'cx')
  end

  def parse_as_include_path
    parse_include_path(get_pattern('as'), 'as')
  end

  def parse_flags(source_pattern, type)
    find_source_obj = false
    defines_line = ''
    @content.each do |line|
      if line.match(source_pattern)
        find_source_obj = true
        defines_line = ''
        next
      end
      if find_source_obj
        # Capture DEFINES line (from target_compile_definitions)
        defines_match = line.match(/DEFINES\s=\s*([\S\s]+)\s*/)
        if defines_match
          defines_line = defines_match[1]
        end

        pattern = /FLAGS\s=\s*([\S\s]+)\s*/
        result = line.match(pattern)
        if result
          combined = (defines_line + ' ' + result[1]).strip
          all_flags = preprocess_flags_with_prefix(split_respecting_quotes(combined))
          all_flags.each do |flag|
            case flag
            when /-D([\"A-Za-z0-9_\(\)]+)=?(.*)?/
              _flag = flag.match(/-D([\"A-Za-z0-9_\(\)]+)=?(.*)?/)
              if _flag[2] && _flag[2] != ''
                if _flag[2].strip.match(/\S+,\S+/) && @toolchain == 'mdk'
                    # mdk GUI define does not support A=B,C add it in misc flags
                    @data[@name]['contents']['configuration']['tools'][@toolchain]['config'][@config]["#{type}-flags"] << flag
                    next
                elsif _flag[2].match(/^\\\".*(\\\"|\\\"\")$/)
                  if @toolchain == 'mdk'
                    # mdk GUI define does not support quotes, add it in misc flags
                    @data[@name]['contents']['configuration']['tools'][@toolchain]['config'][@config]["#{type}-flags"] << flag
                    next
                    # handle case like -D"COMPILER_FLAGS=\"-Ohs --no_size_constraints\""
                  elsif _flag[1].start_with?("\"") && _flag[2].end_with?("\"")
                     key = _flag[1].gsub(/^\"/,'')
                     value= _flag[2].gsub(/\"$/, '')
                     @data[@name]['contents']['configuration']['tools'][@toolchain]['config'][@config]["#{type}-define"][key] = value.gsub("\\", '')
                     next
                  else
                    # flags like -DSSCP_CONFIG_FILE=\"fsl_sscp_config_elemu.h\", should be parsed as yml format:
                    # SSCP_CONFIG_FILE: '"fsl_sscp_config_elemu.h"'
                    macro_file_path = _flag[2].gsub("\\\"", '').strip

                    if ENV['standalone'] == 'true'
                      if Utils.path_inside?(macro_file_path, @outdir)
                        # translate path in build dir, for example
                        # -DZPS_GENERATED_FILE=\"C:/sdk-next/mcuxsdk/build/zps_gen.h\" to
                        # ZPS_GENERATED_FILE: '"${ProjDirPath}/zps_gen.h"'
                        value = File.join(get_tool_rootdir(@toolchain), get_relative_path(@outdir, macro_file_path));
                      elsif Utils.path_inside?(macro_file_path, ENV['SdkRootDirPath'])
                        # translate path in repo dir, for example
                        # -DZPS_GENERATED_FILE=\"C:/sdk-next/mcuxsdk/middleware/wireless/zigbee/examples/zigbee_coordinator/src/zps_gen.h\" to
                        # ZPS_GENERATED_FILE: '"${ProjDirPath}/middleware/wireless/zigbee/examples/zigbee_coordinator/src/zps_gen.h"'
                        value = File.join(get_tool_rootdir(@toolchain), get_relative_path(ENV['SdkRootDirPath'], macro_file_path));
                      else
                        value = macro_file_path
                      end
                      @data[@name]['contents']['configuration']['tools'][@toolchain]['config'][@config]["#{type}-define"][_flag[1]] = "\"#{value}\""
                    else
                      @data[@name]['contents']['configuration']['tools'][@toolchain]['config'][@config]["#{type}-define"][_flag[1]] = _flag[2].gsub("\\", '')
                    end
                    next
                  end
                end
              end
              @data[@name]['contents']['configuration']['tools'][@toolchain]['config'][@config]["#{type}-define"][_flag[1]] = _flag[2].empty? ? nil : _flag[2]
            when /-I-\s(-i|-ir)\s+\"([\S|\s]+)\"/
              _flag = flag.match(/-I-\s(-i|-ir)\s+\"([\S|\s]+)\"/)
              if _flag[2].include?("MCU/DSP56800x_EABI_Tools")
                res = "\\\"${MCUToolsBaseDir}/#{_flag[2].split('/MCU/')[1]}\\\""
              else
                res = "\\\"#{_flag[1]}\\\""
              end
              if _flag[1] == '-i'
                @data[@name]['contents']['configuration']['tools'][@toolchain]['config'][@config]["sys-search-path"] = [] unless @data[@name]['contents']['configuration']['tools'][@toolchain]['config'][@config]["sys-search-path"]
                @data[@name]['contents']['configuration']['tools'][@toolchain]['config'][@config]["sys-search-path"] << {'path' => res}
              elsif _flag[1] == '-ir'
                @data[@name]['contents']['configuration']['tools'][@toolchain]['config'][@config]["sys-path-recursively"] = [] unless @data[@name]['contents']['configuration']['tools'][@toolchain]['config'][@config]["sys-path-recursively"]
                @data[@name]['contents']['configuration']['tools'][@toolchain]['config'][@config]["sys-path-recursively"] << {'path' => res}
              end 
            else
              if @toolchain == 'codewarrior'
                # Codewarrior IDE will add these flags automatically, not need to add them from CMake setting
                next if type == 'as' && (flag.strip == '-msgstyle' || flag.strip == 'parseable' || flag.strip == '-debug')
                next if type == 'cc' && (flag.strip == '-msgstyle' || flag.strip == 'parseable' || flag.strip == '-g')
              end
              @data[@name]['contents']['configuration']['tools'][@toolchain]['config'][@config]["#{type}-flags"] << flag
            end
          end
          break
        end
      end
    end
  end

  def parse_include_path(source_pattern, type)
    find_source_obj = false
    @content.each do |line|
      if line.match(source_pattern)
        find_source_obj = true
        next
      end
      if find_source_obj
        pattern = /INCLUDES\s=\s*([\S\s]+)\s*/
        result = line.match(pattern)
        if result
          # Use scan with a pattern that handles both quoted paths (-I"path with space")
          # and unquoted paths (-I/plain/path), so spaces inside quoted paths are preserved.
          result[1].scan(/-I(?:"([^"]+)"|(\S+))/) do |quoted, unquoted|
            include_dir = (quoted || unquoted)
            path = include_dir.tr('\\', '/')
            if path
              if path.include? REPO_ROOT_PATH
                if path == REPO_ROOT_PATH
                  include_path = './'
                else
                  include_path = path.split(REPO_ROOT_PATH)[-1].sub('/', '')
                end
              else
                begin
                  if ENV['standalone'] == 'true'
                    # if include path is same as output dir for standalone project,
                    # means it's in project root path, use './'
                    if Pathname.new(path).cleanpath == Pathname.new(@outdir).cleanpath
                      include_path = './'
                    else
                      # Use path relative to output dir for standalone project if the file is out of the repo
                      include_path = Pathname.new(path).relative_path_from(Pathname.new(File.join(@outdir, @toolchain))).to_s
                    end
                  else
                    # Use relative path for GUI project
                    include_path = Pathname.new(path).relative_path_from(Pathname.new(REPO_ROOT_PATH)).cleanpath.to_s
                  end
                rescue StandardError => e
                  raise "Get relative path error: Can't get relative path from #{REPO_ROOT_PATH} to #{path}, please make sure the destination path is in the same disk for Windows"
                end
              end

              @data[@name]['contents']['modules']['demo']["#{type}-include"].push({
                                                                          'path' => include_path,
                                                                          'package_path' => include_path,
                                                                          'project_path' => include_path
                                                                        })
            end
          end
          break
        end
      end
    end
  end

  def parse_source
    source_pattern = /^build\sCMakeFiles(\S+\.\S+)\.o(bj)?:/
    @content.each_with_index do |line, index|
      result = line.match(source_pattern)
      if result
        file_full_path = nil
        case Utils.detect_os
        when 'windows'
          file_full_path = line.split(/\s+/)[3]
          file_full_path = file_full_path.sub('$:', ':')
        when /linux|mac/
          file_full_path = line.split(/\s+/)[3]
        end
        if file_full_path
          add_file(file_full_path, line, 'src')
        else
          @logger.error("parse source error: #{@ninja} line #{index + 1}: #{line}.")
        end
      end
    end
  rescue StandardError => e
    @logger.error("parse_source error: #{e.message} ")
  end

  def parse_header
    file_list = File.join(ENV['build_dir'], "#{@name}_source_list.txt")
    if File.exist?(file_list)
        content = File.read(file_list)
        content.strip.split(";").each do |file|
            add_file(file, content, 'c_include') if ['.h', '.hpp', '.inc'].include?(File.extname(file))
            # copy file to repo incase it's necessary for standalone project but not found in build.ninja
            copy_repo_file(file) if File.exist?(file) if ENV['standalone'] == 'true'
        end
    end
  end

  def parse_exclude_files
    file_list = File.join(ENV['build_dir'], "#{@name}_exclude_source_list.txt")
    if File.exist?(file_list)
        content = File.read(file_list)
        content.strip.split(";").each do |file|
            next if file.nil? || file.strip.empty?
            add_file(file, content, 'other', nil, true)
        end
    end
  end

  def parse_libraries
    find_link_obj = false
    @content.each do |line|
      if line.match( /^build\s#{@name}\.elf:/)
        find_link_obj = true
        next
      end
      if find_link_obj
        pattern = /LINK_LIBRARIES\s=\s*([\S\s]+)\s*/
        result = line.match(pattern)
        if result
          # Parse tokens: quoted strings ("...") are treated as one token (path may contain spaces)
          link_libraries = result[1].scan(/"[^"]*"|\S+/)
          link_libraries&.each do |file_full_path|
            # Strip surrounding double quotes if present
            file_full_path = file_full_path.gsub(/\A"(.*)"\z/, '\1')
            next if ["-Wl,--start-group", "-Wl,--end-group"].include? file_full_path
            # skip system library
            unless %w[.a .o .lib].include? File.extname(file_full_path)
            # for xtensa, should be put in ld-flags
             if @toolchain == "xtensa"
                @data[@name]['contents']['configuration']['tools'][@toolchain]['config'][@config]["ld-flags"] << file_full_path
             end
             next
            end
            add_file(file_full_path, line, 'lib', 'extra-libraries')
          end
          break
        end
      end
    end
  end

  def add_file(file_full_path, line, type, attribute = nil, exclude = false)
    file_path = file_full_path.tr('\\', '/')
    
    unless File.exist?(file_path)
      @non_existent_files.push_uniq file_path
      # Ignore non-existent source files into build to prevent build error. 
      # The library file is an exception, becasue it is set in linker flags, could be created by other project
      return unless attribute == 'extra-libraries'
    end

    if file_path.include? REPO_ROOT_PATH
      # when the file is inside the repo
      file_path = file_path.split(REPO_ROOT_PATH)[-1].sub('/', '')
    elsif file_path.include? "#{@name}.dir/"
      file_path = file_path.split("#{@name}.dir/")[1]
      base_path = ENV['APPLICATION_SOURCE_DIR'].split(REPO_ROOT_PATH)[-1].sub('/', '')
      file_path = File.join(base_path, file_path)
    elsif Utils.path_inside?(file_path, File.join(@outdir, "../")) && File.dirname(file_path) != @outdir
      # Special handling for ${APPLICATION_BINARY_DIR}/.. paths
      file_path = Pathname.new(file_full_path).relative_path_from(Pathname.new(File.join(@outdir, @toolchain))).to_s
    else
      file_path = get_relative_path(REPO_ROOT_PATH, file_path)
    end
    # some toolchain like mdk may remove file extension in ninja file, need to add it back for gui project
    file_path = complete_path(file_path, line, attribute) if @toolchain == 'mdk'
    return if file_path.nil?
    source_hash = {
      'source' => file_path,
      'type' => type,
      'project_path' => File.dirname(file_path),
      'repo_path' => File.dirname(file_path),
      'package_path' => File.dirname(file_path)
    }
    source_hash['attribute'] = attribute if attribute
    source_hash['exclude'] = exclude if exclude
    
    # Codewarrior use "build" as build folder, can not set source file to this folder
    if @toolchain == 'codewarrior' && source_hash['project_path'] == 'build'
      source_hash['project_path'] = 'build_dir'
    end
    @data[@name]['contents']['modules']['demo']['files'].push(source_hash)
  end

  def parse_ld_flags
    find_link_obj = false
    source_pattern = /^build\s#{@name}\.elf:/
    @content.each do |line|
      if line.match(source_pattern)
        find_link_obj = true
        next
      end
      if find_link_obj
        pattern = /LINK_FLAGS\s=\s*([\S\s]+)\s*/
        result = line.match(pattern)
        if result
          if @toolchain == 'mcux'
            all_flags = []
            tmp_flags = result[1].split(/\s+/)
            xlinker_flag = false
            tmp_flags.each do |flag|
              if flag == '-Xlinker'
                xlinker_flag = true
                next
              end
              if xlinker_flag
                all_flags << "-Xlinker #{flag}"             
                xlinker_flag = false
              else
                all_flags << flag
              end
            end
          elsif @toolchain == 'codewarrior'
            # Codewarrior IDE will add these flags automatically, not need to add them from CMake setting
            all_flags = result[1].gsub('-bin -gap-fill 0xff -flash-start-x 0x20000', '')
            all_flags = all_flags.gsub('-msgstyle', '').gsub('parseable', '').gsub('-g', '')
            all_flags = parse_ld_script(all_flags).split(/\s+/)
          else
            # Parse tokens: quoted strings ("...") are treated as one token (path may contain spaces)
            raw_tokens = parse_ld_script(result[1]).scan(/"[^"]*"|\S+/)
            all_flags = raw_tokens.map { |t| t.gsub(/\A"(.*)"\z/, '\1') }
          end
          all_flags = preprocess_flags_with_prefix(all_flags)
          all_flags.each do |flag|
            @data[@name]['contents']['configuration']['tools'][@toolchain]['config'][@config]["ld-flags"] << flag
          end
          break
        end
      end
    end
  end

  def parse_ld_script(all_flags)
    case @toolchain
    when 'iar'
      pattern = /--config\s(\S+)\s/
    when 'mdk'
      pattern = /--scatter\s(\S+)\s/
    when 'armgcc'
      pattern = /-T\s(\S+)\s/
    when 'codewarrior'
      pattern = /(\S+Internal_PFlash_(SDM|LDM|HPM|LPM|SPM).cmd)/
    else
      pattern = nil
    end
    if pattern
      result = all_flags.match(pattern)
    else
      result = nil
    end
    if result
      path = get_relative_path(REPO_ROOT_PATH, result[1].tr('\\', '/'))
      tmp = { 'source' => path,
              'attribute' => 'linker-file',
              'toolchains' => @toolchain,
              'targets' => @config,
              'type' => 'linker',
              'project_path' => File.dirname(path),
              'repo_path' => File.dirname(path),
              'package_path' => File.dirname(path)
            }
      tmp['generated'] = true unless File.exist?(result[1])
      @data[@name]['contents']['modules']['demo']['files'].push(tmp)
      all_flags.sub!(result[ 0 ], '')
    end
    all_flags
  end
  # Reconstitute a flag whose path was split at spaces in the build directory.
  # Concatenates subsequent tokens (from all_flags[index+1] onward) with a space
  # until the block returns true or the next token looks like a new flag (starts with '-').
  # Consumed tokens are set to nil in all_flags.
  def reconstitute_flag_with_spaces(all_flags, index)
    full = all_flags[index].strip
    look_ahead = index + 1
    while !yield(full) && look_ahead < all_flags.length &&
          all_flags[look_ahead] && !all_flags[look_ahead].strip.start_with?('-')
      full = "#{full} #{all_flags[look_ahead]}"
      all_flags[look_ahead] = nil
      look_ahead += 1
    end
    full
  end

  #for preifx like --preinclude/--include/--config_def may have several configs, must keep the prefix for each config
  def preprocess_flags_with_prefix(all_flags)
    keep_prefix = ["--preinclude", "-include", "--config_def",  "-P", "--diag_suppress", "-Xlinker", "--redirect"]
    result = []

    all_flags.each_with_index do |flag, index|
        next if flag.nil? || flag.strip.empty?
        if keep_prefix.include?(flag.strip)
          # update relative path for preinclude file
          config_file = all_flags[index+1].delete_prefix('"').delete_suffix('"')
          if File.exist?(config_file)
            path = translate_project_relative_path(config_file)
            if @toolchain == 'iar'
              all_flags[index+1] = File.join('$PROJ_DIR$', path)
            elsif @toolchain == 'xtensa'
              all_flags[index+1] = File.join('${xt_project_loc}', path)
            elsif @toolchain == 'codewarrior'
              all_flags[index+1] = File.join('${ProjDirPath}', path)
            else
              all_flags[index+1] = path
            end
          elsif config_file.start_with?('-Map=')
            # translate map file path for standalone project
            all_flags[index+1] = translate_to_standalone_path(config_file)
          end
          if flag.strip == "--config_def"
            result.push "#{flag}=#{all_flags[index+1]}"
          else
            result.push "#{flag} #{all_flags[index+1]}"
          end
          all_flags[index+1] = nil
        elsif flag.strip.start_with?("--image_input=")
          pattern = /--image_input=(.+),(\S+),(\S+),(\d+)/
          full_flag = reconstitute_flag_with_spaces(all_flags, index) { |s| s.match?(pattern) }
          res = full_flag.match(pattern)
          if res && res[1]
            # If using relative path in cmake setting, need to transfer it to absolute path first, then get path relative to project path
            if res[1].start_with?('../') || res[1].start_with?('./')
              path = File.join('$PROJ_DIR$', translate_project_relative_path(File.join(ENV['build_dir'], res[1])))
            else
              path = File.join('$PROJ_DIR$', translate_project_relative_path(res[1], true))
            end
            result.push full_flag.gsub(res[1], path)
          end
        elsif flag.strip.start_with?("-Wl,--out-implib=")
          full_path = reconstitute_flag_with_spaces(all_flags, index) { |s| s.match?(/\.(o|a|lib)$/) }
                        .sub('-Wl,--out-implib=', '')
          # output lib are put into project root path; quote the path so it is handled
          # correctly by the linker when ProjDirPath resolves to a path with spaces
          path = File.join('${ProjDirPath}', File.basename(full_path))
          result.push "-Wl,--out-implib=\\\"#{path}\\\""
        elsif flag.strip.start_with?("--import_cmse_lib_out=")
          full_path = reconstitute_flag_with_spaces(all_flags, index) { |s| s.match?(/\.(o|a|lib)$/) }
                        .sub('--import_cmse_lib_out=', '')
          result.push "--import_cmse_lib_out=#{full_path}"
        elsif flag.strip.match(/-D([\"A-Za-z0-9_\(\)]+)=?(.*)?/)
          _flag = flag.match(/-D([\"A-Za-z0-9_\(\)]+)=?(.*)?/)
          if _flag[2] && _flag[2] != ''
            # if macro value like \"-Ohs without ending \",  means there is a space in macro value
            if _flag[2].start_with?("\\\"") && !_flag[2].end_with?("\\\"")
              result.push "#{flag} #{all_flags[index+1]}"
              all_flags[index+1] = nil
            else
              result.push flag
            end
          else
            result.push flag
          end
        elsif @toolchain == 'codewarrior'
          if flag.strip == '-I-'
            # for codewarrior, "-I -i path" and "-I -ir path" should be seen as a whole
            result.push "#{flag} #{all_flags[index+1]}  #{all_flags[index+2]} #{all_flags[index+3]}"
            for i in 1..3
              all_flags[index+i] = nil
            end
          elsif ['-data', '-prog', '-opt'].include? flag.strip
            result.push "#{flag} #{all_flags[index+1]}"
            all_flags[index+1] = nil
          elsif (lib_match = flag.strip.match(/\A-L(?!arge)\s*"?([^"]+?)"?\z/))
            # Extract -L<path> or -L"<path>" -> config => lib-search-path
            lib_path = lib_match[1].sub(/[\/\\]+\z/, '')
            lib_path = translate_project_relative_path(lib_path, true) if File.absolute_path?(lib_path)
            cfg = @data[@name]['contents']['configuration']['tools'][@toolchain]['config'][@config]
            cfg["lib-search-path"] ||= []
            cfg["lib-search-path"] << {'path' => lib_path} unless cfg["lib-search-path"].any? { |e| e['path'] == lib_path }
          else
            pattern = /-l\"(\S+)MCU\/(DSP56800x_EABI_Tools\/lib\S+)\"/
            res = flag.strip.match(pattern)
            if res && res[2]
              result.push "-l\\\"${MCUToolsBaseDir}/#{res[2]}\\\""
            else
              result.push flag
            end
          end
        elsif flag
          result.push flag
        end
    end
    result
  end

  # translate absolute path to path relative to project root path
  def translate_project_relative_path(abs_path, path_from_other_project = false)
    relative_path = Pathname.new(abs_path).relative_path_from(Pathname.new(@outdir)).to_s
    if ENV['standalone'] == 'true'
      if relative_path.start_with?('..')
        # for path from other project, need extra '..' in path, because the project file is in <build_dir>/toolchain folder
        if path_from_other_project && ENV['SYSBUILD']
          # if the file exists in repo, but not in build folder, it will be copied to standalone project folder, so use the path relative to project root path
          # for example: examples/_boards/evkmimxrt685/dsp_examples/mu_interrupt/hifi4/binary/dsp_text_release.bin
          if File.exist?(abs_path) && Utils.path_inside?(abs_path, ENV['SdkRootDirPath']) && Utils.path_inside?(abs_path, File.join(@outdir, '..')) == false
            path = Pathname.new(abs_path).relative_path_from(ENV['SdkRootDirPath']).to_s
          else
            path = File.join('..', relative_path)
          end
        else
          # if the path is for project itself, because all the file is in toolchain folder, and the folder structure is same
          # as repo, we can intercept the rest of REPO_ROOT_PATH from abs_path
          path = abs_path.tr('\\', '/').split(REPO_ROOT_PATH)[-1]
        end
      else
        path = relative_path
      end
    else
      # For gui project, project file is in <build_dir>/toolchain folder, need extra '..' in path
      path = File.join('..', relative_path)
    end
    Pathname.new(File.join('.', path)).cleanpath.to_s
  end

  def remove_last_quote_if_odd(str)
    return nil if str.nil? || str.empty?

    quote_count = str.count("'\"")
    if quote_count.odd? && ["'", '"'].include?(str[-1])
      # delete the last quotation mark
      str.chop!
    end
    str
  end

  def translate_path_in_build_cmd(content)
    repo_root_dir = File.basename(ENV['SdkRootDirPath'])
    project_root_dir = File.join(@outdir, @toolchain)
    cmd_list = content.split(" && ")
    cmd_list.each_with_index do |cmd_item, index|
      # Filter out cmd.exe wrapper and bare "cd <build_dir>" navigation commands that Ninja
      # emits around every custom command on Windows. These are build-system artifacts and
      # must not appear as COMMAND entries in the generated CMakeLists.txt.
      # The trailing "* allows for zero or more closing quotes, which CMake adds when the
      # build directory path contains spaces (e.g. "cd "C:\path\m 2"" ends with two quotes).
      cmd_list[index] = nil if cmd_item.match(/(cmd.exe|cd)[\s\S]+[\/\\]#{File.basename(@outdir)}"*$/)
      # Add space between -I and path to handle path separately
      if cmd_list[index] && cmd_list[index].match(/\s-I\S+/)
        cmd_list[index] = cmd_list[index].sub(/\s-I/, ' -I ')
      end
      cmd_list[index] = remove_last_quote_if_odd(cmd_list[index])
    end
    cmd_list = split_respecting_quotes(cmd_list.compact.join(' && '))
    # TODO Identify more toolchains if necessary
    cmd_list.each_with_index do |item, index |
      # copy file in build command in case it's not add by mcux_add_source
      if ENV['standalone'] && File.file?(item.strip) && Utils.path_inside?(item.strip, ENV['SdkRootDirPath'])
        dest_path = File.join(@outdir, @toolchain, get_relative_path(ENV['SdkRootDirPath'], File.dirname(item.strip)))
        FileUtils.mkdir_p(dest_path)
        FileUtils.cp_r(item.strip, dest_path)
      end

      # Remove the absolute path to python
      if File.basename(item).include?('python') && File.exist?(item)
        cmd_list[index] = File.basename(item, ".*")
        next
      end

      # Use toolchain build-in variale for absolute path to toolchain folder
      translated_path = translate_toolchain_path_variable(item)
      if translated_path != item
        cmd_list[index] =  translated_path
        next
      end
      if item.match(/-[Io](\S+)/)
        path = item.include?(repo_root_dir) && item.match(/-[Io](\S+)/)[1]
        if File.exist?(path)
          if ENV['standalone'] == 'true'
            dest_path = File.join(File.join(@outdir, @toolchain), path.split(/#{repo_root_dir}[\/\\]/)[-1])
            new_path = get_relative_path(File.join(@outdir, @toolchain), dest_path)
          else
            new_path = get_relative_path(File.join(@outdir, @toolchain), path)
          end
          if item.strip.start_with?('-I')
            cmd_list[index] = "-I#{new_path}"
          else
            cmd_list[index] = "-o#{new_path}"
          end
        end
      elsif item.include?(project_root_dir) || item.include?(@outdir)
        cmd_list[index] = translate_to_standalone_path(item)
      elsif item.include?(repo_root_dir) && File.exist?(File.dirname(item))
        # translate path in mcuxsdk
        if ENV['standalone'] == 'true'
          cmd_list[index] = translate_to_standalone_path(item)
        else
          cmd_list[index] = get_relative_path(File.join(@outdir, @toolchain), item)
        end
      end
    end
    cmd_list = cmd_list.join(' ').split(' && ')
    cmd_list.map! {|cmd_str|  remove_last_quote_if_odd(cmd_str)}
  end

  def parse_prebuild
    pattern = /PRE_LINK\s=\s(.*)/
    @content.each do |line|
      result = line.match(pattern)
      if result
        content = result[1].strip
        # cd . means no cmd
        break if content == 'cd .' || content == ':'
        cmd_list = translate_path_in_build_cmd(content)
        # Decide how to rewrite the absolute cmake executable path embedded
        # in PRE_LINK by CMake:
        #   armgcc/riscvllvm → ${CMAKE_COMMAND} (re-processed by CMake at build time)
        #   IDE + standalone → bare `cmake` (rely on PATH for portability)
        #   IDE + in-tree GUI → leave the absolute build-time path
        cmake_replacement =
          if %w[armgcc riscvllvm].include? @toolchain
            ' ${CMAKE_COMMAND}'
          elsif ENV['standalone'] == 'true'
            ' cmake'
          end
        if cmake_replacement
          cmd_list.each_with_index do |cmd_str, index|
            # translate cmake executable path, if starts with quote, indicates there is space in path
            # Use [^"]* to match any character except quote before cmake executor
            pattern = /"?[^"]*[\/\\]cmake(\.exe)?"|\s*\S+[\/\\]cmake(\.exe)?/
            result = cmd_str.match(pattern)
            while(result)
              cmd_list[index] = cmd_str.sub(result[ 0 ], cmake_replacement)
              result = cmd_str.match(cmd_list[index])
            end
          end
        end

        cmd_list = cmd_list.map { |c| wrap_for_mdk_shell(c) } if @toolchain == 'mdk'

        @logger.debug( "Parse prebuild command: #{cmd_list.join(' ')}")
        if NO_GUI_TEMPLATE_TOOLCHAIN.include? @toolchain
          @data[@name]['contents']['configuration']['tools'][@toolchain]['prebuild'] = cmd_list
        else
          @data[@name]['contents']['configuration']['tools'][@toolchain]['prebuild'] = cmd_list
        end
        break
      end
    end
  end

  # MDK uVision executes BeforeMake/AfterMake User Programs directly without
  # a shell. When the command needs shell semantics, wrap it in `cmd /C "..."` so
  # the Windows command processor parses the metacharacters. Idempotent.
  def wrap_for_mdk_shell(cmd)
    cmd = cmd.to_s.strip
    return cmd if cmd.empty?
    return cmd if cmd.start_with?('cmd /C ', 'cmd.exe /C ', 'cmd /c ', 'cmd.exe /c ')
    return cmd unless cmd.match?(/[><|]|&&/)
    "cmd /C \"#{cmd}\""
  end

  def parse_postbuild
    pattern = /POST_BUILD\s=\s(.*)/
    @content.each do |line|
      result = line.match(pattern)
      if result
        content = result[1].strip
        # match binary convert command, unless there are extra process by other tool such as python
        if content.match(/\S+?.elf/) && content.match(/\S+(.bin|.srec|.hex)/) && content.match(/(-Obinary|--bin|-Osrec|--srec|--m32|-Oihex|--ihex|--i32)/) && !content.include?("python")
          bin_file = File.basename(content.match(/\S+\.(bin|srec|hex)/)[0])
          @data[@name]['contents']['configuration']['tools'][@toolchain]['binary-file'] = bin_file

          # If there is copy command after binary convert, need to keep it in postbuild command
          unless content.include?("-E copy")
            break
          else
            content = content.split("#{bin_file} &&")[-1].strip
          end
        elsif content.match(/\s*(CMakeFiles\S+post-build.bat)\s\d+/)
          # If post build command is too long for Windows, it wiil be saved in post-build.bat file
          # need to read and parse it
          post_build_bat = content.match(/\s*(CMakeFiles\S+post-build.bat)\s\d+/)[1]
          post_build_bat = File.join(@outdir, post_build_bat)
          if File.exist?(post_build_bat)
            # Read and parse the post-build.bat file
            parse_postbuild_bat_file(bat_file_path)
            break
          end
        end
        
        # cd . means no postbuild cmd
        if content == 'cd .' || content == ':'
          break
        elsif @toolchain == 'iar'
          if ENV['project_type']  == 'LIBRARY'
            pattern = /\s\S+lib#{@name}\.a/
          else
            pattern = /\s\S+#{@name}\.elf/
          end
          result = content.match(pattern)
          while(result)
            content.sub!(result[ 0 ], ' $TARGET_PATH$')
            result = content.match(pattern)
          end
        elsif @toolchain == 'mdk'
          if ENV['project_type']  == 'LIBRARY'
              pattern = /\s\S+lib#{@name}\.a/
              result = content.match(pattern)
              while(result)
              content.sub!(result[ 0 ], ' $p/#L')
              result = content.match(pattern)
            end
          else
            pattern = /--bincombined\s\S+#{@name}\.elf/
            result = content.match(pattern)
            content.sub!(result[ 0 ], '--bincombined $p/#L') if result
          end
        elsif %w[armgcc riscvllvm].include? @toolchain
          # translate project elf/lib to $<TARGET_FILE:${MCUX_SDK_PROJECT_NAME}>
          if ENV['project_type']  == 'LIBRARY'
            pattern = /\s\S+lib#{@name}\.a/
          else
            pattern = /\s\S+#{@name}\.elf/
          end
          result = content.match(pattern)
          while(result)
            content.sub!(result[ 0 ], ' $<TARGET_FILE:${MCUX_SDK_PROJECT_NAME}>')
            result = content.match(pattern)
          end
          # translate cmake to ${CMAKE_COMMAND}, if starts with quote, indicates there is space in path
          # Use [^"]* to match any character except quote before cmake executor
          pattern = /\s"[^"]*bin[\/\\]cmake(\.exe)?"|\s\S+bin[\/\\]cmake(\.exe)?/
          result = content.match(pattern)
          while(result)
            content.sub!(result[ 0 ], ' ${CMAKE_COMMAND}')
            result = content.match(pattern)
          end
        end
        cmd_list = translate_path_in_build_cmd(content)

        if NO_GUI_TEMPLATE_TOOLCHAIN.include? @toolchain
          @data[@name]['contents']['configuration']['tools'][@toolchain]['postbuild'] = cmd_list
        else
          @data[@name]['contents']['configuration']['tools'][@toolchain]['postbuild'] = cmd_list
        end
        break
      end
    end
  end

  def parse_postbuild_bat_file(bat_file_path)
    bat_content = File.readlines(bat_file_path)
    cmd_list = []
    bat_content.each_with_index do |bat_line, index|
      # Skip batch control lines
      next if bat_line.match(/^@echo off/)
      next if bat_line.match(/^cd \/D/)
      next if bat_line.match(/^\(set FAIL_LINE=/)
      next if bat_line.match(/^goto :/)
      next if bat_line.match(/^:ABORT/)
      next if bat_line.match(/^set ERROR_CODE=/)
      next if bat_line.match(/^exit \/b/)
      next if bat_line.strip.empty?
      
      # Extract the actual command (remove error handling)
      if bat_line.match(/\|\|\s*\(set FAIL_LINE=\d+&\s*goto :ABORT\)/)
        command = bat_line.split(/\|\|/).first.strip
      else
        command = bat_line.strip
      end
      
      translated_cmd = translate_path_in_build_cmd(command)
      cmd_list << translated_cmd.join(' && ') if translated_cmd && !translated_cmd.empty?
    end

    cmd_list&.each do |cmd|
      if @toolchain == 'armgcc'
        @data[@name]['contents']['configuration']['tools'][@toolchain]['cmake_command'] ||= []
        raw_command =  <<~HEREDOC
          add_custom_command(
            TARGET
            ${MCUX_SDK_PROJECT_NAME}
            POST_BUILD
            COMMAND
            #{cmd}
          )
        HEREDOC
        @data[@name]['contents']['configuration']['tools'][@toolchain]['cmake_command'].push(raw_command)
      else
        @data[@name]['contents']['configuration']['tools'][@toolchain]['postbuild'] ||= []
        @data[@name]['contents']['configuration']['tools'][@toolchain]['postbuild'].push(cmd.chomp)
      end
    end  
  end

  def parse_precompile
    cmd_list = []
    pattern = /build\sCMakeFiles(\/|\\)PRE_COMPILE_CMD_TARGET/
    @content.each_with_index do |line, index|
      result = line.match(pattern)
      if result
        content = @content[index+1].strip
        if content.include?('COMMAND = ')
          cmd = content.split('COMMAND = ')[-1]
          cmd_list << cmd
        end
      end
    end
    @data[@name]['contents']['configuration']['tools'][@toolchain]['precompile'] = cmd_list if cmd_list
  end

  # If the command is added by native add_custom_command without build events, the build command 
  # can not be found in POST_BUILD/PRE_LINK variable from build.ninja, need special handling
  def parse_cmake_custom_command
    parse_source_file_generation_command
  end

  # special handing for file generation command not added by mcux_add_custom_command
  # For example:
  # add_custom_command(
  #       PRE_BUILD
  #       OUTPUT
  #       ${APPLICATION_BINARY_DIR}/pdum_gen.c
  #       ${APPLICATION_BINARY_DIR}/pdum_gen.h
  #       ${APPLICATION_BINARY_DIR}/pdum_apdu.S
  #       COMMAND ${PYTHON_EXECUTABLE} ${PDUMCONFIG}
  #       ARGS 
  #       -z coordinator
  #       -e ENDIAN
  #       -f ${ZPSCFG}
  #       -o ${APPLICATION_BINARY_DIR}
  # )
  def parse_source_file_generation_command
    cmd_list = []
    pattern = /#\sCustom\scommand\sfor\s(\S+)/
    @content.each_with_index do |line, index|
      result = line.match(pattern)
      if result
        # Filter out known command for guiproject, kconfig and so on
        next if CUSTOM_COMMAND_IGNORE_LIST.include? File.basename(result[1].strip)
        # If the file is recorded in @non_existent_files, which means it does not exist,
        # need to parse the command for file generation
        if !@non_existent_files.include? File.join(@outdir, result[1].strip)
          if !result[1].include?('preprocess_linker_file')
            next
          end
        end
        
        content = @content[index+3].strip
        # Find the command
        if content.include?('COMMAND = ')
          cmd = content.split('COMMAND = ')[-1]
          # handle the command for file generation
          if @content[index+4].strip.include?("DESC = Generating ")
            cmd = translate_path_in_build_cmd(cmd)
            generated_file = @content[index+4].split(" Generating ")[1].split(', ').map {|file| File.join(get_tool_rootdir(@toolchain), file)}
            cmd_list << {'file'=> generated_file.join(' ').chomp, 'command' => cmd.join(' && ').chomp}
          elsif result[1].include?('preprocess_linker_file')
            # special handling for linker file generation command
            parse_linker_bat_file(cmd, cmd_list)
          end
        end
      end
    end

    cmd_list&.each do |cmd|
      if @toolchain == 'armgcc'
        @data[@name]['contents']['configuration']['tools'][@toolchain]['cmake_command'] ||= []
        raw_command =  <<~HEREDOC
          add_custom_command(
            OUTPUT
            #{cmd['file']}
            COMMAND
            #{cmd['command']}
          )

          target_sources(${MCUX_SDK_PROJECT_NAME} PRIVATE 
            #{cmd['file']}
          )
        HEREDOC
        @data[@name]['contents']['configuration']['tools'][@toolchain]['cmake_command'].push(raw_command)
      else
        @data[@name]['contents']['configuration']['tools'][@toolchain]['prebuild'] ||= []
        @data[@name]['contents']['configuration']['tools'][@toolchain]['prebuild'].push(cmd['command'])
      end
    end
  end

  # Surface component-side `add_custom_target(<name> COMMAND ...)`
  # + `add_dependencies(${MCUX_SDK_PROJECT_NAME} <name>)` as prebuild commands
  # in the generated IDE / standalone project.
  #
  # CMake/Ninja does NOT inline such custom_target COMMANDs into the main
  # target's PRE_LINK variable — it only wires them as order-only deps after
  # `||` on the link build edge. `parse_prebuild` therefore never sees them.
  # Walk those order-only deps, resolve each phony rule down to its
  # CUSTOM_COMMAND block, extract `COMMAND = ...`, sanitize, and append to
  # the prebuild list.
  def parse_custom_target_dependencies
    # Locate the link build edge for the main project target.
    link_pattern = /^build\s+#{Regexp.escape(@name)}\.(elf|a)\s*:/
    link_line = @content.find { |line| line.match(link_pattern) }
    return unless link_line
    return unless link_line.include?('||')

    # Everything after `||` is the order-only dependency list.
    order_only_part = link_line.split('||', 2)[1].strip
    order_only_deps = order_only_part.split(/\s+/).reject(&:empty?)

    custom_commands = []
    order_only_deps.each do |dep|
      dep_basename = File.basename(dep.tr('\\', '/'))
      # Skip CMake/Ninja internal aggregators and well-known SDK targets
      # already handled elsewhere or never meant to surface as a prebuild.
      next if CUSTOM_COMMAND_IGNORE_LIST.include?(dep_basename)
      next if dep_basename.start_with?('cmake_')
      next if dep_basename == "#{@name}.elf" || dep_basename == "#{@name}.a"
      # mcux_add_custom_command(BUILD_EVENT PRE_COMPILE) custom targets are
      # named PRE_COMPILE_CMD_TARGET_<MD5> and are picked up by parse_precompile.
      next if dep_basename.start_with?('PRE_COMPILE_CMD_TARGET_')

      # Follow the phony rule to its CUSTOM_COMMAND target.
      phony_pattern = /^build\s+#{Regexp.escape(dep)}\s*:\s*phony\s+(\S+)/
      phony_line = @content.find { |line| line.match(phony_pattern) }
      next unless phony_line

      cmakefiles_path = phony_line.match(phony_pattern)[1]
      custom_cmd_pattern = /^build\s+#{Regexp.escape(cmakefiles_path)}.*:\s+CUSTOM_COMMAND/
      custom_idx = @content.find_index { |line| line.match(custom_cmd_pattern) }
      next unless custom_idx

      # COMMAND = ... lives in the variable block under the
      # `build ...: CUSTOM_COMMAND` line.
      ((custom_idx + 1)...@content.length).each do |i|
        next_line = @content[i]
        break if next_line.start_with?('build ') || next_line.start_with?('#')
        cmd_match = next_line.match(/COMMAND\s*=\s*(.*)/)
        if cmd_match
          custom_commands << cmd_match[1].strip
          break
        end
      end
    end

    return if custom_commands.empty?

    cmake_replacement =
      if %w[armgcc riscvllvm].include? @toolchain
        ' ${CMAKE_COMMAND}'
      elsif ENV['standalone'] == 'true'
        ' cmake'
      end

    translated_commands = []
    custom_commands.each do |raw_cmd|
      # Strip the Ninja Windows shell wrapper that CMake emits around custom
      # command bodies.
      raw_cmd = raw_cmd.sub(/^[^"]*cmd\.exe\s+\/C\s+"cd\s+\/D\s+.+?\s*&&\s*/, '')
      raw_cmd = raw_cmd.sub(/"\s*$/, '')

      translated = translate_path_in_build_cmd(raw_cmd)
      translated = [translated] unless translated.is_a?(Array)
      translated.each do |cmd_str|
        if cmake_replacement
          pattern = /"?[^"]*[\/\\]cmake(\.exe)?"|\s*\S+[\/\\]cmake(\.exe)?/
          result = cmd_str.match(pattern)
          while(result)
            cmd_str = cmd_str.sub(result[0], cmake_replacement)
            result = cmd_str.match(pattern)
          end
        end
        translated_commands << cmd_str
      end
    end

    return if translated_commands.empty?

    existing = @data.dig(@name, 'contents', 'configuration', 'tools', @toolchain, 'prebuild') || []
    combined = existing + translated_commands

    # MDK uvprojx schema only exposes two prebuild commands.
    # For >2 prebuild commands, concatenate commands 2..N into
    # the second slot with ` && ` so the IDE still runs
    # all of them in order. Other toolchains accept N entries natively.
    if @toolchain == 'mdk' && combined.length > 2
      combined = [combined.first, combined[1..-1].join(' && ')]
    end

    combined = combined.map { |c| wrap_for_mdk_shell(c) } if @toolchain == 'mdk'

    @data[@name]['contents']['configuration']['tools'][@toolchain]['prebuild'] = combined
  end

  def parse_example_readme
    return unless ENV['APPLICATION_SOURCE_DIR']

    example_yml_path = File.join(ENV['APPLICATION_SOURCE_DIR'], 'example.yml')
    return unless File.exist?(example_yml_path)

    example_data = YAML.load_file(example_yml_path)
    return unless example_data.is_a?(Hash)

    # Find matching example entry by @name, or fall back to the first entry
    example_entry = example_data[@name] || example_data.values.first
    return unless example_entry.is_a?(Hash)

    readme_list = example_entry.dig('contents', 'document', 'example_readme')
    return unless readme_list.is_a?(Array)

    readme_list.each do |readme_path|
      next unless readme_path.is_a?(String)

      # Expand ${var} patterns using environment variables (e.g. ${board}, ${board_root})
      expanded_path = readme_path.gsub(/\$\{(\w+)\}/) { ENV[$1] || $& }

      full_path = File.join(REPO_ROOT_PATH, expanded_path)
      unless File.exist?(full_path)
        @logger.debug("example_readme file not found, skipping: #{expanded_path}")
        next
      end

      source_hash = {
        'source' => expanded_path,
        'type' => 'doc',
        'project_path' => File.dirname(expanded_path),
        'repo_path' => File.dirname(expanded_path),
        'package_path' => File.dirname(expanded_path)
      }
      @data[@name]['contents']['modules']['demo']['files'].push(source_hash)
    end
  rescue StandardError => e
    @logger.error("parse_example_readme error: #{e.message}")
  end

  def parse_linker_bat_file(cmd, cmd_list)
    bat_file_path = nil
    if cmd.match(/\S+preprocess_linker_file-\S+\.bat/)
      bat_file = cmd.match(/(\S+preprocess_linker_file-\S+\.bat)/)[1]
      bat_file_path = File.join(ENV['build_dir'], bat_file).tr('\\', '/')
    end
  
    # read the .bat file to get the generated linker file
    if bat_file_path && File.exist?(bat_file_path)
      pattern = /(.*\.(ld|icf|scf)).*.*\|\|/
      file = File.open(bat_file_path, 'rb')
      bat_content = file.readlines
      generated_file = nil
      bat_content.each_with_index do |bat_line, index|
        result = bat_line.match(pattern)
        if result
          cmd = translate_path_in_build_cmd(result[1].tr("\\", '/').tr(';', ' '))
          generated_file = if @toolchain == 'iar'
            result[1].split(/\s+/)[-2]
          else
            result[1].split(/\s+/)[-1].delete_suffix('"').delete_suffix("'")
          end
          break
        end
      end

      if generated_file
        cmd_list << {'file'=> File.join(get_tool_rootdir(@toolchain), File.basename(generated_file)), 'command' => cmd.join(' && ').chomp}   
      end
    else
      generated_file = if @toolchain == 'iar'
            cmd.split(/\s+/)[-2]
          else
            cmd.split(/\s+/)[-1].delete_suffix('"').delete_suffix("'")
          end
      cmd = translate_path_in_build_cmd(cmd.split('&&')[-1].strip)
      cmd_list << {'file'=> File.join(get_tool_rootdir(@toolchain), File.basename(generated_file)), 'command' => cmd.join(' && ').chomp}
    end
  end

  def complete_path(file_path, line, attribute = nil)
    source_ext = %w[.c .cpp .s .S .cc]
    full_path = File.join(REPO_ROOT_PATH, file_path)
    if File.exist?(full_path)
      return file_path
    elsif attribute == 'extra-libraries'
      return file_path
    else
      source_ext.each do |ext|
        tmp = full_path + ext
        # make sure the file exsit and the file ext name is exact same as build.ninja without letter case error, such as .S .s for file extension name
        if File.exist?(tmp) && line.include?(File.basename(tmp))
          return get_relative_path(REPO_ROOT_PATH, tmp)
        end
      end
    end
    @logger.error("complete path error: #{file_path} does not exist.")
    nil
  end

  def get_relative_path(base_path, taeget_path)
    base = Pathname.new(base_path)
    target = Pathname.new(taeget_path)
    target.relative_path_from(base).to_s
  end

  def merge_ide_data
    @variables = {}
    ENV.each do |key, value|
      @variables[key] = value
    end
    # codewarrior cp-define use CONFIG_MCUX_HW_DEVICE_ID
    @variables['CONFIG_MCUX_HW_DEVICE_ID'] =  @variables['device_id']

    file_list = ENV['IDE_YML_LIST']&.split(' ')
    ide_data = {}
    if NO_GUI_TEMPLATE_TOOLCHAIN.include?(@toolchain)
      ide_data.deep_merge!(reorg_ide_data({
        @toolchain=> {
          'project-templates' => ["scripts/guigenerator/templates/cmake/CMakeLists.txt",
                                  "cmake/toolchain/#{@toolchain}.cmake"]
        },
        'cmake_toolchain' => {
          'files' => [
            {'source' => "scripts/guigenerator/templates/cmake/toolchain/#{@toolchain}.cmake", 'type' => 'script', 'package_path' => 'cmake/toolchain', "exclude" => true},
            {'source' => "scripts/guigenerator/templates/cmake/toolchain/toolchain.cmake", 'type' => 'script', 'package_path' => 'cmake/toolchain', "exclude" => true},
            {'source' => "scripts/guigenerator/templates/cmake/toolchain/mcux_config.cmake", 'type' => 'script', 'package_path' => 'cmake/toolchain', "exclude" => true}
          ]
        }
      }))
    else
      raise "Error: No IDE.yml found." if ENV['IDE_YML_LIST'].nil? || ENV['IDE_YML_LIST'].empty?
    end
    file_list.each do |file|
      if File.extname(file) == '.yml'
        @logger.debug( "Merge IDE data #{file}")
        content = YAML.load_file(file)
        ide_data.deep_merge!(reorg_ide_data(content), {:overwrite_arrays => true})
      end
    end
    merge_by_variable(ide_data)
    merge_by_common!(ide_data)
    process_project_path(ide_data)

    if @logger.level == Logger::DEBUG
      dump_file = File.join(ENV['build_dir'], 'IDE.yml')
      @logger.debug("Dump merged IDE.yml into #{ENV['build_dir']}/IDE.yml")
      YAML.dump_file(dump_file, ide_data)
    end

    # For settings in YML_OVERRIDE_TOOL_CONFIG_SETTINGS, yml takes precedence
    # over CMake-parsed data: drop the CMake side under any tool where the yml
    # already defines one, so the deep_merge below does not concatenate the
    # two arrays.
    drop_cmake_yml_override_settings(ide_data, @data)

    @data.deep_merge!(ide_data)
  end

  # For each setting listed in YML_OVERRIDE_TOOL_CONFIG_SETTINGS:
  # if the yml defines it for a tool (under any config target), remove that
  # setting from every config target of the same tool in the CMake-parsed
  # @data before merging. This makes the yml override the CMake value rather
  # than concatenating the two arrays.
  def drop_cmake_yml_override_settings(yml_content, cmake_content)
    return if yml_content.nil? || cmake_content.nil?
    return if yml_content[@name].nil? || cmake_content[@name].nil?
    yml_tools   = yml_content[@name].dig('contents', 'configuration', 'tools')
    cmake_tools = cmake_content[@name].dig('contents', 'configuration', 'tools')
    return if yml_tools.nil? || cmake_tools.nil?

    yml_tools.each do |tool_name, tool_content|
      next unless tool_content.is_a?(Hash)
      yml_configs = tool_content['config']
      next unless yml_configs.is_a?(Hash)
      cmake_configs = cmake_tools.dig(tool_name, 'config')
      next unless cmake_configs.is_a?(Hash)

      YML_OVERRIDE_TOOL_CONFIG_SETTINGS.each do |setting|
        yml_has_setting = yml_configs.any? do |_target, target_content|
          target_content.is_a?(Hash) && target_content.key?(setting)
        end
        next unless yml_has_setting

        cmake_configs.each_value do |target_content|
          target_content.delete(setting) if target_content.is_a?(Hash)
        end
      end
    end
  end

  def reorg_ide_data(content)
    tmp = {
      '__variable__' => {},
      @name => {
        'contents' => {
          'configuration' => {
            'tools'=> {
              @toolchain => {
                'config' => {
                  @config => {
                  }
                }
              }
            }
          },
          'modules' => {
          }
        }
      }
    }
    content&.each do |key, value|
      next unless value

      if key == @toolchain
        tmp[@name]['contents']['configuration']['tools'][@toolchain].deep_merge! value
      elsif key == '__variable__'
        tmp['__variable__'].deep_merge! value
      elsif value.key? 'files'
        tmp[@name]['contents']['modules'][key] = value
      end
    end
    tmp.delete('__variable__') if tmp['__variable__'].empty?
    tmp
  end

  def merge_by_variable(yml_data_content)
    return if Hash != yml_data_content.class

    yml_data_content['__variable__']&.each do |key, val|
      if @variables.key?(key) && @variables[key] != val
        @logger.fatal("Yml variable \"#{key} => #{val}\" dose not match cmake variable \"#{key} => #{@variables[key]}\", please change variable name or update variable value in IDE.yml")
      end
      @variables[key] = val
    end

    yml_data_content.each do |key, value|
      next if yml_data_content[key].class != Hash

      value_iterator(@variables, value)
    end

    key_iterator(@variables, yml_data_content)
  end

  # handle project-root-path and project-name in IDE.yml
  def process_project_path(ide_data)
    project_path_variables = {
      'project-root-path' => './',
      'project-name' => @name
    }
    ide_data.each do |project_name, content|
      content['contents']['modules'].each do |mod_name, mod_content|
        mod_content['files']&.each do |file|
          file.each do |key, value|
            project_path_variables.each do |variable_name, variable_value|
              value.gsub!(/#{variable_name}/, variable_value) if value.is_a?(String)
            end
          end
          file['repo_path'] = File.dirname(file['source']) unless file.key?('repo_path')
        end
      end
    end
  end

  def value_iterator(variables, value)
    if Hash == value.class
      value.each_value { |v| value_iterator(variables, v) }
    elsif Array == value.class
      value.each { |v| value_iterator(variables, v) }
    elsif String == value.class
      value.gsub!(/\${(\w+)}/) do |match|
        var_name = $+
        resolved = variables[var_name]
        if resolved
          resolved
        else
          @logger.info("variable '#{var_name}' does not exist, keep '${#{var_name}}' as is")
          match
        end
      end
    end
  end

  def key_iterator(variables, data)
    case data
    when Hash
      data.transform_keys! do |key|
        key.gsub(/\${(\w+)}/) do |_match|
          Core.assert(variables[::Regexp.last_match(-1)],
                      "variable '#{::Regexp.last_match(-1)}' is used in yml record, but has not been defined under '__variable__'")
          variables[::Regexp.last_match(-1)]
        end
      end
      data.each do |key, value|
        key_iterator(variables, value)
      end
    when Array
      data.each do |value|
        key_iterator(variables, value)
      end
    end

    data
  end

  def merge_project_segments(project_segments, section_content)
    project_segments&.each do |each_segment, each_content|
      next if each_content['section-type'] != 'project_segment'
      next if each_content['required'] != true

      segment_data = deep_copy(each_content)
      segment_data.safe_delete('section-type')
      segment_data.safe_delete('merge_segment')
      segment_data.safe_delete('belong_to')

      section_content.deep_merge!(segment_data)
    end
    section_content
  end

  def merge_by_common!(yml_data_content)
    return if Hash != yml_data_content.class

    unless yml_data_content['__common__'].nil?
      yml_data_content.each_key do |subnode|
        next if KEY_LIST.include?(subnode)
        next if (yml_data_content[subnode].class != Hash) || (yml_data_content['__common__'].class != Hash)

        yml_data_content[subnode] = yml_data_content[subnode].deep_merge!(deep_copy(yml_data_content['__common__']))
      end
      yml_data_content.delete('__common__')
    end
    yml_data_content.each_key { |subnode| merge_by_common!(yml_data_content[subnode]) }
  end

  def merge_by_replace!(yml_data_content)
    return if Hash != yml_data_content.class
    _merge_by_replace!(yml_data_content)
    yml_data_content.each_key do |key|
      merge_by_replace!(yml_data_content[key]) if Hash == yml_data_content[key].class
    end
  end

  def _merge_by_replace!(yml_data_content)
    return if Hash != yml_data_content.class
    # get the replace hash
    return unless yml_data_content.key?('__replace__')

    temp = {}
    temp = temp.deep_merge(deep_copy(yml_data_content['__replace__']))
    temp.each_key do |key|
      next unless yml_data_content.key?(key)

      delete_node(yml_data_content, key)
      yml_data_content[key] = temp[key]
    end
    yml_data_content.delete('__replace__')
  end

  def delete_node(yml_data_content, type, items = nil)
    yml_data_content.each_key do |subnode|
      next if yml_data_content[subnode].nil?

      if items
        items.each { |item| yml_data_content[type].delete(item) }
      else
        yml_data_content.delete(type)
      end
      delete_node(yml_data_content[subnode], type) if Hash == yml_data_content[subnode].class
    end
  end

  def update_overlay(overlay_data)
    overlay_data.each do |node, overlay|
      update_iterate_nested_hash(@data, node.split('/'), overlay)
    end
  end

  def update_iterate_nested_hash(hash, sub_keys, content)
    if hash.is_a?(Hash)
      if hash.dig(*sub_keys)
        if sub_keys.length == 1
          hash[sub_keys.last] = content
        else
          hash.dig(*sub_keys[0..-2])[sub_keys.last] = content
        end
        return
      end
    end
    hash.each do |key, value|
      if value.is_a?(Hash)
        update_iterate_nested_hash(value, sub_keys, content)
      end
    end
  end

  def set_project_language
    unless @data[@name]['contents']['configuration']['tools'][@toolchain].key?('project_language')
      cx_flags =  @data[@name]['contents']['configuration']['tools'][@toolchain]['config'][@config]['cx-flags']
      unless cx_flags.empty?
        case @toolchain
        when 'mdk', 'armgcc'
          @data[@name]['contents']['configuration']['tools'][@toolchain]['project_language'] = 'cpp'
        when 'iar'
          @data[@name]['contents']['configuration']['tools'][@toolchain]['project_language'] = 'auto'
        end
      end
    end
  end


  def remove_unsupported_config
    @data[@name]['contents']['configuration']['tools'][@toolchain]['config'].each do |key, content|
      if key != @config
        @data[@name]['contents']['configuration']['tools'][@toolchain]['config'].delete(key)
        next
      end

      %w[cc-define cx-define as-define cc-flags as-flags cx-flags ld-flags cp-define].each do |setting|
        @data[@name]['contents']['configuration']['tools'][@toolchain]['config'][key].delete(setting) if content[setting].empty?
      end

    end
  end

  def copy_repo_file(src_path)
    # copy repo file to build_dir/toolchain folder
    if Utils.path_inside?(src_path, ENV['SdkRootDirPath']) && !Utils.path_inside?(src_path, @outdir)
      relative_path = Pathname.new(src_path).relative_path_from(ENV['SdkRootDirPath']).to_s
      if !File.exist?(src_path)
        @logger.error("File #{src_path} recorded from CMake does not exist, please check the file path.")
      elsif File.directory?(src_path)
        @logger.error("Dierctory #{src_path} should not be recorded in mcux_add_source, only file type is supported. Please check CMake setting.")
      else
        FileUtils.cp_f(src_path, File.join(@outdir, @toolchain, relative_path))
      end
    end
  end

  def get_tool_rootdir(tool)
    case tool
    when 'iar'
      return '$PROJ_DIR$'
    when 'mdk'
      return '$P'
    when 'armgcc', 'codewarrior'
      return '${ProjDirPath}'
    when 'xtensa'
      return '${xt_project_loc}'
    else
      return '.'
    end
  end

  # Split a command string by spaces while preserving quoted substrings as single tokens.
  # This handles toolchain paths that contain spaces, e.g.:
  #   "C:\Program Files (x86)\Arm GNU Toolchain arm-none-eabi\14.2 rel1\bin\arm-none-eabi-gcc.exe"
  # Also handles backslash-escaped spaces (e.g. Ninja-style: /path/m\ 2/armgcc),
  # treating the backslash-space as a literal space within the token.
  def split_respecting_quotes(str)
    tokens = []
    current = ''
    in_quote = false
    chars = str.chars
    i = 0
    while i < chars.length
      c = chars[i]
      if c == '"'
        in_quote = !in_quote
        current += c
      elsif c == '\\' && !in_quote && i + 1 < chars.length && chars[i + 1] == ' '
        # Backslash-escaped space: include the space in the current token without the backslash
        current += ' '
        i += 1
      elsif (c == ' ' || c == "\t") && !in_quote
        tokens << current unless current.empty?
        current = ''
      else
        current += c
      end
      i += 1
    end
    tokens << current unless current.empty?
    tokens
  end

  def translate_toolchain_path_variable(path)
    ext_name = Utils.detect_os == 'windows' ? '.exe' : ''
    # translate toolchain folder
    if File.exist?(File.join(path, "lib/gcc/arm-none-eabi"))
      return "${TOOLCHAIN_DIR}"
    elsif File.exist?(File.join(path, "bin/armclang#{ext_name}"))
      return "$KARM/ARMCLANG"
    elsif File.exist?(File.join(path, "bin/iccarm#{ext_name}"))
      return "$TOOLKIT_DIR$"
    elsif path.match(/bin[\/\\]iccarm/)
      return "$TOOLKIT_DIR$/bin/iccarm"
    elsif path.match(/bin[\/\\]ielftool/)
      return "$TOOLKIT_DIR$/bin/ielftool"
    elsif path.match(/bin[\/\\]armclang/)
      return "$KARM/ARMCLANG/bin/armclang"
    elsif path.match(/bin[\/\\]fromelf/)
      return "$KARM/ARMCLANG/bin/fromelf"
    elsif path.match(/bin[\/\\]arm-none-eabi-gcc/)
      return "${TOOLCHAIN_DIR}/bin/arm-none-eabi-gcc"
    elsif path.match(/bin[\/\\]arm-none-eabi-objcopy/)
      return "${TOOLCHAIN_DIR}/bin/arm-none-eabi-objcopy"
    else
      return path
    end
  end
  
  # translate path to standalone project path
  def translate_to_standalone_path(path)
    if !ENV['standalone'] || ENV['standalone'] != 'true'
      return path
    end

    # Strip surrounding quotes that CMake/Ninja adds when paths contain spaces
    unquoted = path.delete_prefix('"').delete_suffix('"')
    if unquoted.include?(File.join(@outdir, @toolchain))
      # translate path in build/${toolchain} for standalone project.
      # eg, build/armgcc/mcux_config.h to $PROJ_DIR$/mcux_config.h
      return unquoted.gsub(File.join(@outdir, @toolchain), get_tool_rootdir(@toolchain))
    elsif unquoted.include?(@outdir)
      # translate path in build for standalone project, because it will be copied to build/${toolchain}.
      #. eg, build/pdum_gen.h to $PROJ_DIR$/pdum_gen.h
      return unquoted.gsub(@outdir, get_tool_rootdir(@toolchain))
    elsif unquoted.include?(File.basename(ENV['SdkRootDirPath']))
      dest_path = File.join(File.join(@outdir, @toolchain), unquoted.split(/#{File.basename(ENV['SdkRootDirPath'])}[\/\\]/)[-1])
      return File.join(get_tool_rootdir(@toolchain), get_relative_path(File.join(@outdir, @toolchain), dest_path))
    else
      return path
    end
  end

end